### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [alwayslearnedstuff/prj-rev-bwfs-tea-cozy#1]
This project is hard to judge as it matches our solution perfectly.

If I am wrong, then you did excellent as I could not tell the difference between this and the solution on hand.

Including comments, class names, the number of lines in css.

The only difference I can see is that the link to the css is different than the solution.

There is no failure here, but this project is not reviewable when it is like this.

Sometimes we have learners who ask for the solution so they can see how things are done.
They do change things enough to make this project their own.

If you want, you can upload your version of Tea Cozy here and I will look over it, and give you corrections on how to fix any issues you were having.

**Comment by alwayslearnedstuff** [comment]
Thanks, Farish. I'll aim to revise.

Jon
